- src/main/resources/templates/partials.html
> navbar changes

- src/main/java/com/example/springblog/controllers/ProductController.java
- src/main/resources/templates/partials.html
- src/main/resources/templates/products/create.html
- src/main/resources/templates/products/edit.html
- src/main/resources/templates/products/index.html
- src/main/resources/templates/users/login.html
ctrl + g changed all post methods to product fixed
> ctrl + g changed all post methods to product

- src/main/java/com/example/springblog/controllers/HomeController.java
- src/main/java/com/example/springblog/models/Product.java
- src/main/java/com/example/springblog/models/User.java
- src/main/java/com/example/springblog/repo/UserRepository.java
- src/main/resources/templates/users/login.html
> updated User model and database

- pom.xml
- src/main/java/com/example/springblog/controllers/HomeController.java
- src/main/resources/static/local.css
- src/main/resources/static/uikit.css
- src/main/resources/static/uikit.js
- src/main/resources/templates/home.html
- src/main/resources/templates/partials.html
- src/main/resources/templates/products/create.html
- src/main/resources/templates/products/edit.html
- src/main/resources/templates/products/index.html
- src/main/resources/templates/products/show.html
- src/main/resources/templates/users/login.html
- src/main/resources/templates/users/sign-up.html
> implemented Uikit with CDN and also refactored everything

- src/main/java/com/example/springblog/controllers/UserController.java
- src/main/java/com/example/springblog/models/User.java
- src/main/java/com/example/springblog/models/UserWithRoles.java
- src/main/java/com/example/springblog/repo/UserRepository.java
- src/main/java/com/example/springblog/repo/Users.java
- src/main/resources/templates/error/4xx.html
- src/main/resources/templates/error/500.html
- src/main/resources/templates/partials.html
- src/main/resources/templates/users/sign-up.html
> fixing roles, updating db, updating errors

- src/main/java/com/example/springblog/controllers/UserController.java
- src/main/java/com/example/springblog/models/UserRole.java
- src/main/java/com/example/springblog/models/UserWithRoles.java
- src/main/java/com/example/springblog/repo/UserRepository.java
- src/main/java/com/example/springblog/repo/UserRoleRepository.java
- src/main/java/com/example/springblog/services/UserDetailsLoader.java
- src/main/java/com/example/springblog/services/UserRepository.java
- src/main/java/com/example/springblog/services/UserService.java
- src/main/resources/templates/home.html
I made Roles 100% functional and ready to make the pages for admin page, driver page, and customer page!
> Roles create

- src/main/java/com/example/springblog/controllers/ProductController.java
- src/main/java/com/example/springblog/controllers/UserController.java
- src/main/java/com/example/springblog/models/Product.java
- src/main/resources/templates/partials.html
let me know what you think about the navbar changes, roles are fully implemented for users now, will start working on the functionality for the admin create product page
> got certain navbars to display when certain users are logged in

- src/main/java/com/example/springblog/models/Product.java
- src/main/resources/templates/products/index.html
quick change for functioning categories
> categories fixed and custom queries for categories being made

- src/main/java/com/example/springblog/controllers/ProductController.java
- src/main/java/com/example/springblog/repo/CategoryRepository.java
- src/main/java/com/example/springblog/repo/ProductRepository.java
- src/main/java/com/example/springblog/services/ProductService.java
> cat crud for seeder

- src/main/java/com/example/springblog/controllers/ProductController.java
- src/main/java/com/example/springblog/models/Product.java
- src/main/java/com/example/springblog/repo/ProductRepository.java
- src/main/java/com/example/springblog/services/ProductService.java
- src/main/resources/templates/partials.html
- src/main/resources/templates/products/create.html
- src/main/resources/templates/products/edit.html
- src/main/resources/templates/products/index.html
Looks rlly spicy!!! got category sorting working! lmk what you think and next up is SecurityAuth for certain roles.
> category sorting works! also added an edit category feature

- src/main/java/com/example/springblog/components/DatabaseSeeder.java
- src/main/java/com/example/springblog/controllers/UserController.java
- src/main/java/com/example/springblog/repo/CategoryRepository.java
- src/main/java/com/example/springblog/repo/UserRepository.java
check this out , all the features for category sort with seeder file!
> working seeder and category sort features!

- src/main/java/com/example/springblog/components/DatabaseSeeder.java
- src/main/java/com/example/springblog/models/Product.java
- src/main/resources/templates/products/create.html
- src/main/resources/templates/products/edit.html
- src/main/resources/templates/products/index.html
- src/main/resources/templates/products/show.html
> adding my special spices to the mix

- src/main/java/com/example/springblog/controllers/UserController.java
- src/main/resources/templates/users/profile.html
edit profile is now based on what user is logged it
> edit profile made working when a user is authenticated

- src/main/resources/templates/shoppingCart.html
fixed a small change it add-to-cart title page
> cart fixed

- src/main/java/com/example/springblog/components/DatabaseSeeder.java
- src/main/java/com/example/springblog/components/Methods.java
- src/main/java/com/example/springblog/controllers/ShoppingCartController.java
- src/main/java/com/example/springblog/models/Order.java
- src/main/java/com/example/springblog/models/OrderStatus.java
- src/main/java/com/example/springblog/models/Product.java
- src/main/java/com/example/springblog/repo/UserRepository.java
- src/main/java/com/example/springblog/services/ShoppingCartService.java
- src/main/resources/templates/checkoutSuccess.html
- src/main/resources/templates/shoppingCart.html
check this out, stripe api works and creates a order! Just need to get the dates that fernando was talking about.
> got the stripe api work to create a order, looking good!!!

- src/main/java/com/example/springblog/components/DatabaseSeeder.java
- src/main/java/com/example/springblog/components/Methods.java
- src/main/java/com/example/springblog/controllers/ShoppingCartController.java
- src/main/java/com/example/springblog/repo/OrderRepository.java
- src/main/java/com/example/springblog/repo/OrderStatusRepository.java
- src/main/java/com/example/springblog/services/ShoppingCartService.java
- src/main/resources/templates/checkoutSuccess.html
- src/main/resources/templates/home.html
- src/main/resources/templates/products/index.html
allows the user to create order after payment is made, pull and check it out
> working stripe api that needs some minor changes

- src/main/java/com/example/springblog/controllers/ShoppingCartController.java
- src/main/java/com/example/springblog/models/Product.java
- src/main/resources/templates/products/create.html
- src/main/resources/templates/products/edit.html
- src/main/resources/templates/shoppingCart.html
> Stripe api

- src/main/java/com/example/springblog/components/Methods.java
- src/main/resources/templates/drivers.html
date and time added for orders, check it out
> date and time added for orders

- src/main/java/com/example/springblog/controllers/DriverController.java
- src/main/java/com/example/springblog/controllers/UserController.java
- src/main/java/com/example/springblog/models/User.java
- src/main/java/com/example/springblog/repo/OrderRepository.java
- src/main/resources/templates/drivers.html
- src/main/resources/templates/home.html
- src/main/resources/templates/orders/order_show.html
- src/main/resources/templates/partials.html
- src/main/resources/templates/products/index.html
- src/main/resources/templates/products/show.html
- src/main/resources/templates/users/profile.html
fixed a few of the driver/admin pages and also built out the driver dashboard
> Driver pages

- src/main/java/com/example/springblog/models/Product.java
- src/main/resources/templates/drivers.html
- src/main/resources/templates/partials.html
- src/main/resources/templates/shoppingCart.html
> driver page is now compact for the drivers viewing

- pom.xml
- src/main/java/com/example/springblog/components/DatabaseSeeder.java
- src/main/java/com/example/springblog/components/SlackApi.java
- src/main/resources/templates/checkoutSuccess.html
- src/main/resources/templates/partials.html
- src/main/resources/templates/products/index.html
- src/main/resources/templates/users/profile.html
added the images to each product
> added images to each product

- src/main/java/com/example/springblog/components/DatabaseSeeder.java
- src/main/java/com/example/springblog/controllers/DriverController.java
- src/main/java/com/example/springblog/controllers/UserController.java
- src/main/java/com/example/springblog/repo/UserRepository.java
- src/main/java/com/example/springblog/services/UserService.java
- src/main/resources/templates/drivers.html
- src/main/resources/templates/home.html
- src/main/resources/templates/orders/order_show.html
- src/main/resources/templates/orders/user_show.html
- src/main/resources/templates/partials.html
- src/main/resources/templates/products/index.html
- src/main/resources/templates/products/show.html
changes to img_urls and also fade animation speed and few other things
> made many changes to img_urls

- src/main/java/com/example/springblog/controllers/DriverController.java
- src/main/java/com/example/springblog/services/SmsSender.java
- src/main/resources/templates/home.html
- src/main/resources/templates/partials.html
- src/main/resources/templates/products/index.html
- src/main/resources/templates/shoppingCart.html
got twilio to work and cleaned up all of the product cards on all pages
> Twilio api

- src/main/java/com/example/springblog/controllers/UserController.java
- src/main/java/com/example/springblog/repo/UserRepository.java
- src/main/resources/templates/home.html
- src/main/resources/templates/partials.html
- src/main/resources/templates/products/index.html
- src/main/resources/templates/users/profile-edit.html
- src/main/resources/templates/users/profile.html
> User check

- src/main/resources/templates/about.html
- src/main/resources/templates/home.html
- src/main/resources/templates/partials.html
mobile responsive navbar and also made the about section lined up properly
> made navbar mobile responsive

- src/main/resources/templates/home.html
just made margin on home products page
> margin top added to the products section on home page
